Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -8,7 +8,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
@@ -33,22 +32,45 @@ jobs:
           # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
-      
-
-      - name: Test with e2e.py
+      - name: Test with pytest
         run: |
-          python tests/e2e.py
+          pytest
 
-      - name: Set up Docker
+      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
       - name: Login to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      - name: Build and push Docker image
+      - name: Build Docker image
+        run: docker build -t tannvi/project .
+
+      - name: Start Docker Compose
+        run: docker-compose up -d
+
+      - name: Wait for the application to start
         run: |
-          docker build -t tannvi/project .
-          docker push tannvi/project
+          max_retries=10
+          retries=0
+          while ! curl -s http://localhost:5000 > /dev/null; do
+            retries=$((retries + 1))
+            if [ $retries -ge $max_retries ]; then
+              echo "Application failed to start within the timeout period"
+              exit 1
+            fi
+            echo "Waiting for application to start..."
+            sleep 5
+          done
+
+      - name: Run e2e tests inside Docker container
+        run: docker-compose exec scoreservice python tests/e2e.py
+
+      - name: Push Docker image
+        run: docker push tannvi/getting-started
+        if: success()
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Shutdown Docker Compose
+        run: docker-compose down
